// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-situations.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var SITUATIONS = [
  { slug: "decider-sans-visibilite", title: "D\xE9cider sans visibilit\xE9", summary: "Prendre des d\xE9cisions strat\xE9giques dans un environnement opaque, sans rep\xE8res fiables." },
  { slug: "attaques-informationnelles", title: "Attaques informationnelles", summary: "Faire face \xE0 des campagnes de d\xE9stabilisation, rumeurs ou attaques r\xE9putationnelles cibl\xE9es." },
  { slug: "deficit-attractivite", title: "D\xE9ficit d'attractivit\xE9", summary: "Restaurer l'attractivit\xE9 aupr\xE8s des talents, investisseurs ou partenaires strat\xE9giques." },
  { slug: "crises-non-maitrisees", title: "Crises non ma\xEEtris\xE9es", summary: "Reprendre le contr\xF4le narratif et op\xE9rationnel lors d'une crise en cours." },
  { slug: "perte-velocite", title: "Perte de v\xE9locit\xE9", summary: "Retrouver la capacit\xE9 d'ex\xE9cution et la vitesse d\xE9cisionnelle face \xE0 des concurrents plus agiles." },
  { slug: "deficit-influence", title: "D\xE9ficit d'influence", summary: "Structurer et amplifier son influence aupr\xE8s des d\xE9cideurs et \xE9cosyst\xE8mes cl\xE9s." },
  { slug: "investir-sous-risque", title: "Investir sous risque", summary: "S\xE9curiser une d\xE9cision d'investissement strat\xE9gique face \xE0 l'incertitude et \xE0 l'asym\xE9trie d'information." },
  { slug: "gouverner-sous-pression", title: "Gouverner sous pression", summary: "Piloter une organisation en environnement politique, r\xE9glementaire ou m\xE9diatique tendu." }
];
var list_situations_default = defineTool({
  name: "list_critical_situations",
  title: "List critical situations",
  description: "Return the 8 critical strategic situations Buildfluence addresses (Sovereign Decision Infrastructure use cases).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SITUATIONS, null, 2) }],
    structuredContent: { situations: SITUATIONS }
  })
});

// src/lib/mcp/tools/list-solutions.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var SOLUTIONS = [
  { slug: "strategic-intelligence-lab", title: "Strategic Intelligence Lab", summary: "Cellule d'intelligence strat\xE9gique d\xE9di\xE9e : veille augment\xE9e, analyse et recommandations op\xE9rationnelles." },
  { slug: "deep-due-diligence", title: "Deep Due Diligence", summary: "Investigation approfondie sur cibles, partenaires ou dirigeants avant d\xE9cision strat\xE9gique majeure." },
  { slug: "soft-power-influence", title: "Soft Power & Influence", summary: "Construction d'une influence durable aupr\xE8s des d\xE9cideurs, \xE9cosyst\xE8mes et publics cl\xE9s." }
];
var CAPABILITIES = [
  { slug: "ai-powered-monitor", title: "AI Powered Monitor", summary: "Veille strat\xE9gique multicanale augment\xE9e par l'IA sur web profond et signaux faibles." },
  { slug: "strategic-workflow", title: "Strategic Workflow", summary: "Structuration d'une unit\xE9 de veille et d'intelligence strat\xE9gique interne." },
  { slug: "strategic-command-center", title: "Strategic Command Center", summary: "Cockpit d\xE9cisionnel : Risques, Opportunit\xE9s, Concurrence, Narratif." },
  { slug: "competitive-velocity-engine", title: "Competitive Velocity Engine", summary: "Mapping dynamique de l'\xE9cosyst\xE8me concurrentiel, R&D et alliances." }
];
var list_solutions_default = defineTool2({
  name: "list_solutions_and_capabilities",
  title: "List solutions & capabilities",
  description: "Return Buildfluence's 3 strategic solutions and 4 advanced capabilities.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify({ solutions: SOLUTIONS, capabilities: CAPABILITIES }, null, 2) }],
    structuredContent: { solutions: SOLUTIONS, capabilities: CAPABILITIES }
  })
});

// src/lib/mcp/tools/submit-access-request.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var submit_access_request_default = defineTool3({
  name: "submit_access_request",
  title: "Submit premium access request",
  description: "Submit a request for Buildfluence Premium access. Persists the request and notifies the Buildfluence team.",
  inputSchema: {
    name: z.string().min(1).describe("Full name of the requester."),
    email: z.string().email().describe("Professional email address."),
    organization: z.string().optional().describe("Company or organization."),
    phone: z.string().optional().describe("Phone number (optional)."),
    message: z.string().optional().describe("Context or message for the Buildfluence team."),
    langue: z.enum(["fr", "en"]).optional().describe("Preferred language (fr or en).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
  handler: async (input) => {
    const supabaseUrl = process.env.SUPABASE_URL;
    const anonKey = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!supabaseUrl || !anonKey) {
      return { content: [{ type: "text", text: "Server misconfigured: missing Supabase env." }], isError: true };
    }
    const res = await fetch(`${supabaseUrl}/functions/v1/send-access-request`, {
      method: "POST",
      headers: { "Content-Type": "application/json", apikey: anonKey, Authorization: `Bearer ${anonKey}` },
      body: JSON.stringify({
        name: input.name,
        email: input.email,
        organization: input.organization ?? "",
        phone: input.phone ?? "",
        message: input.message ?? "",
        langue: input.langue ?? "fr"
      })
    });
    const data = await res.json().catch(() => ({}));
    if (!res.ok) {
      return { content: [{ type: "text", text: `Request failed: ${JSON.stringify(data)}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: "Access request submitted. The Buildfluence team will follow up." }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "buildfluence-mcp",
  title: "Buildfluence MCP",
  version: "0.1.0",
  instructions: "Buildfluence \u2014 Sovereign Decision Infrastructure. Use `list_critical_situations` and `list_solutions_and_capabilities` to explore the offering. Use `submit_access_request` to request Buildfluence Premium access on behalf of a user.",
  tools: [list_situations_default, list_solutions_default, submit_access_request_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
